// Code generated by "stringer -linecomment -type RoughColour"; DO NOT EDIT.

package colour

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RoughlyRed-0]
	_ = x[RoughlyGreen-1]
	_ = x[RoughlyBlue-2]
	_ = x[RoughlyCyan-3]
	_ = x[RoughlyMagenta-4]
	_ = x[RoughlyYellow-5]
	_ = x[RoughlyBlack-6]
	_ = x[RoughlyGrey-7]
	_ = x[RoughlyWhite-8]
	_ = x[RoughlyOther-9]
}

const _RoughColour_name = "RedGreenBlueCyanMagentaYellowBlackGreyWhiteOther"

var _RoughColour_index = [...]uint8{0, 3, 8, 12, 16, 23, 29, 34, 38, 43, 48}

func (i RoughColour) String() string {
	if i < 0 || i >= RoughColour(len(_RoughColour_index)-1) {
		return "RoughColour(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RoughColour_name[_RoughColour_index[i]:_RoughColour_index[i+1]]
}
